version: '3.8'

services:
  you2api:
    build: .
    container_name: you2api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENABLE_PROXY=false
      - PROXY_URL=
      - PROXY_TIMEOUT_MS=5000
      - LOG_LEVEL=info
    restart: unless-stopped
